### ISSUE TITLE
Gatsby - No SSR

### ISSUE THREAD

**Issue by AnDyro751** [Schorts99/azachii-ui-react#1]
Pinche paquete tan más culero, no sirve con gatsby, intenté hacer el ssr pero no carga los estilos, el desarrollador no sabe crear componentes

**Comment by AnDyro751** [comment]
El autor me amenazó con hablarle a su amigo el 1000levantones si no quitaba mi comentario.

#niunomenos

**Comment by Schorts99** [comment]
Jajaja corrígelo huevon

**Comment by AnDyro751** [comment]
Cierro el issue porque me volvió a amenazar.
